version: '3.7'

services:
    # backend API
    smart-brain-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/smart-brain-api
        ports: 
            - "3001:3001"
        volumes: 
            - ./:/usr/src/smart-brain-api
        environment: 
            DATABASE_URL: "postgresql://dockeruser:dockerdb@postgres:5432/smartbrain-docker"
            REDIS_URI: redis://redis:6379
            NODE_ENV: 'docker'
            PORT: '3001'
            JWT_SECRET: '63f0c3dd767245dc9aa24304b526635b'


    # postgres
    postgres:
        container_name: postgres
        build: ./postgres
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: dockeruser
            POSTGRES_PASSWORD: dockerdb
            POSTGRES_DB: smartbrain-docker
            POSTGRES_HOST: postgres

    
    # redis
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"